---
- name: Installation des outils de base
  apt:
    name:
      - vim
      - git
      - curl
      - python3-pip
      - php8.3-fpm
      - python3-dev
      - python3-setuptools
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-pymysql
    state: present
    update_cache: yes
    cache_valid_time: 3600
